/** @type {import('tailwindcss').Config} */
// Design system Étoile OS — aligné sur la maquette Stitch.
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Palette Material 3 étendue (extrait maquette Toile OS)
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#006c4a",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "on-surface-variant": "#3d4a42",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "outline": "#6d7a72",
        "outline-variant": "#bccac0",
        "primary": {
          DEFAULT: "#006948",
          50:  "#f5fff7",
          100: "#c4f5dc",
          200: "#85f8c4",
          300: "#68dba9",
          400: "#4edea3",
          500: "#00855d",
          600: "#006c4a",
          700: "#006948",
          800: "#005137",
          900: "#002114",
        },
        "on-primary": "#ffffff",
        "primary-container": "#00855d",
        "on-primary-container": "#f5fff7",
        "primary-fixed": "#85f8c4",
        "primary-fixed-dim": "#68dba9",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#005137",
        "inverse-primary": "#68dba9",
        "secondary": "#565e74",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#006947",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00855b",
        "on-tertiary-container": "#f5fff6",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        // Alias typographiques de la maquette (font-body-md, font-headline-lg…)
        "caption":     ["Plus Jakarta Sans"],
        "label-sm":    ["Plus Jakarta Sans"],
        "label-md":    ["Plus Jakarta Sans"],
        "label-lg":    ["Plus Jakarta Sans"],
        "body-sm":     ["Plus Jakarta Sans"],
        "body-md":     ["Plus Jakarta Sans"],
        "body-lg":     ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-md":  ["Plus Jakarta Sans"],
        "display-lg":  ["Plus Jakarta Sans"],
      },
      fontSize: {
        "caption":     ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm":    ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md":    ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-lg":    ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm":     ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md":     ["14px", { lineHeight: "20px", letterSpacing: "0",      fontWeight: "400" }],
        "body-lg":     ["16px", { lineHeight: "24px", letterSpacing: "0",      fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em",  fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-md":  ["32px", { lineHeight: "40px", letterSpacing: "-0.02em",  fontWeight: "700" }],
        "display-lg":  ["40px", { lineHeight: "48px", letterSpacing: "-0.02em",  fontWeight: "700" }],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "gutter-compact": "1rem",
        "margin-compact": "1.5rem",
        "gutter": "1.5rem",
        "margin": "2rem",
      },
    },
  },
  plugins: [],
}
