package projet_hotelier.hotel.core.metadata.ennumeration;

public enum CodeReference {

    // GLOBAL
    REF_GLOBAL,
    REF_ORGANISATION,
    REF_HOTEL,
    REF_SITE,
    REF_APPLICATION,

    // CLIENTS & FIDÉLITÉ
    REF_CLIENT,
    REF_CLIENT_PRO,
    REF_CLIENT_DIASPORA,
    REF_CLIENT_VIP,
    REF_CLIENT_INCONNU,
    REF_PROFIL_FIDELITE,
    REF_CARTE_FIDELITE,
    REF_POINTS_FIDELITE,

    // RÉSERVATION & SÉJOUR
    REF_RESERVATION,
    REF_RESERVATION_GROUPE,
    REF_RESERVATION_AGENCE,
    REF_RESERVATION_ONLINE,
    REF_RESERVATION_OFFLINE,
    REF_SEJOUR,
    REF_CHECKIN,
    REF_CHECKOUT,
    REF_NO_SHOW,
    REF_PROLONGATION_SEJOUR,

    // CHAMBRE & HÉBERGEMENT
    REF_CHAMBRE,
    REF_TARIF_CHAMBRE,
    REF_SURCLASSEMENT,
    REF_CHANGEMENT_CHAMBRE,
    REF_INCIDENT_CHAMBRE,

    // FACTURATION & PAIEMENT
    REF_FACTURE,
    REF_FACTURE_PROFORMA,
    REF_FACTURE_TVA,
    REF_NOTE_CREDIT,
    REF_NOTE_DEBIT,
    REF_AVOIR,
    REF_PAIEMENT,
    REF_PAIEMENT_MOBILE_MONEY,
    REF_PAIEMENT_CARTE,
    REF_PAIEMENT_CHEQUE,
    REF_PAIEMENT_ESPECE,
    REF_REMBOURSEMENT,
    REF_LITIGE,
    REF_REFUND,
    REF_ADJUSTMENT,
    REF_REVERSEMENT,

    // RH
    REF_EMPLOYE,
    REF_CONTRAT,
    REF_RECRUTEMENT,
    REF_CV,
    REF_CANDIDATURE,
    REF_PRESENCE,
    REF_CONGE,
    REF_ABSENCE,
    REF_SALAIRE,
    REF_BULLETIN,
    REF_EVALUATION_PERFORMANCE,

    // SUPPORT & INCIDENT
    REF_TICKET_SUPPORT,
    REF_INCIDENT,
    REF_INTERVENTION,
    REF_PLAN_ACTION,
    REF_ESCALADE,
    REF_SLA,

    // STOCK & ACHAT
    REF_PRODUIT,
    REF_CATEGORIE_PRODUIT,
    REF_INVENTAIRE,
    REF_ENTREE_STOCK,
    REF_SORTIE_STOCK,
    REF_COMMANDE_FOURNISSEUR,
    REF_RECEPTION_COMMANDE,
    REF_FACTURE_FOURNISSEUR,

    // RESTAURATION & BAR
    REF_COMMANDE_RESTO,
    REF_FACTURE_RESTO,
    REF_TICKET_RESTO,
    REF_MENU,
    REF_PLAT,
    REF_BOISSON,

    // SPA & BIEN-ÊTRE
    REF_COMMANDE_SPA,
    REF_RESERVATION_SPA,
    REF_PRESTATION_SPA,

    // ÉVÉNEMENTIEL
    REF_EVENEMENT,
    REF_RENSEIGNEMENT_EVENEMENT,
    REF_TICKET_EVENEMENT,
    REF_CONTRAT_EVENEMENT,

    // MARKETING
    REF_CAMPAGNE,
    REF_PROMO,
    REF_COUPON,
    REF_PROGRAMME_PARTENARIAT,
    REF_PARTENARIAT,

    // CONFORMITÉ & AUDIT
    REF_AUDIT,
    REF_JOURNAL_AUDIT,
    REF_CONFORMITE,
    REF_RAPPORT_CONFORMITE,

    // DOCUMENTS
    REF_DOCUMENT,
    REF_ARCHIVAGE_DOCUMENT,

    // INTÉGRATION & API
    REF_API,
    REF_WEBHOOK,
    REF_INTEGRATION_PARTENAIRE,

    // NOTIFICATION
    REF_NOTIFICATION,
    REF_EMAIL,
    REF_SMS,
    REF_PUSH
}
