package projet_hotelier.hotel.core.metadata.ennumeration;

public enum DocumentType {

    // DOCUMENTS CLIENTS
    PIECE_IDENTITE,
    PASSEPORT,
    CARTE_CEDEAO,
    PERMIS_CONDUIRE,
    JUSTIFICATIF_ADRESSE,
    ATTESTATION_RESIDENCE,
    PHOTO_CLIENT,
    CONSENTEMENT_RGPD,

    // DOCUMENTS DE RÉSERVATION
    CONFIRMATION_RESERVATION,
    VOUCHER,
    POLITIQUE_ANNULATION,
    CONDITIONS_SEJOUR,
    CONTRAT_GROUPE,
    CONTRAT_AGENCE,

    // DOCUMENTS D’HÉBERGEMENT
    ETAT_DES_LIEUX,
    RAPPORT_INCIDENT_CHAMBRE,
    CERTIFICAT_ENTRETIEN_CHAMBRE,

    // DOCUMENTS FINANCIERS
    FACTURE,
    FACTURE_PROFORMA,
    NOTE_DE_CREDIT,
    NOTE_DE_DEBIT,
    RECU,
    BORDEREAU_PAIEMENT,
    RAPPORT_FINANCIER,
    DECLARATION_TVA,
    BORDEREAU_CAISSE,

    // DOCUMENTS RH
    CONTRAT_TRAVAIL,
    CV,
    LETTRE_RECRUTEMENT,
    ATTESTATION_EMPLOI,
    FICHE_PERSONNEL,
    DOCUMENT_CONGE,
    DOCUMENT_ABSENCE,
    BULLETIN_DE_PAIE,
    FICHE_EVALUATION,
    FORMULAIRE_ONBOARDING,

    // DOCUMENTS SUPPORT / INCIDENTS
    RAPPORT_INCIDENT,
    PHOTO_INCIDENT,
    RAPPORT_INTERVENTION,
    DOCUMENT_TICKET_SUPPORT,
    PLAN_ACTION_CORRECTIF,

    // DOCUMENTS MAINTENANCE
    PLAN_MAINTENANCE,
    RAPPORT_MAINTENANCE,
    CERTIFICAT_ENTRETIEN,
    GARANTIE_EQUIPMENT,
    MANUEL_EQUIPMENT,

    // DOCUMENTS STOCK / ACHAT
    BON_DE_COMMANDE,
    BON_DE_RECEPTION,
    FACTURE_FOURNISSEUR,
    FICHE_INVENTAIRE,
    ETAT_STOCK,
    FICHE_PRODUIT,
    FICHE_FOURNISSEUR,

    // DOCUMENTS RESTAURATION / SPA
    MENU,
    RECETTE,
    FICHE_ALLERGENES,
    CERTIFICAT_HYGIENE,
    PLAN_CUISINE,
    PROTOCOLE_SPA,

    // DOCUMENTS MARKETING
    BROCHURE,
    CATALOGUE,
    PLAQUETTE,
    CONTRAT_PARTENARIAT,
    PLAN_COMMUNICATION,
    RAPPORT_CAMPAGNE,

    // DOCUMENTS ÉVÉNEMENTIELS
    CONTRAT_EVENEMENT,
    PLAN_EVENEMENT,
    BUDGET_EVENEMENT,
    LISTE_INVITES,
    RAPPORT_POST_EVENEMENT,

    // DOCUMENTS LÉGAUX / CONFORMITÉ
    DOCUMENT_RGPD,
    DOCUMENT_CONFORMITE,
    DOCUMENT_AUDIT,
    POLITIQUE_SECURITE,
    POLITIQUE_CONFIDENTIALITE,
    PROCÈS_VERBAL,
    LICENCE_EXPLOITATION,
    CERTIFICAT_SECURITE,
    CERTIFICAT_INCENDIE,

    // DOCUMENTS ADMINISTRATIFS
    NOTE_DE_SERVICE,
    PROCÈS_VERBAL_REUNION,
    COMPTE_RENDU,
    DOCUMENT_INTERNE,

    // DOCUMENTS DIVERS
    IMAGE,
    PDF,
    AUTRE
}
