package projet_hotelier.hotel.module.rh.mapper.employe;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import projet_hotelier.hotel.module.rh.dto.request.employe.CreateEmployeRequest;
import projet_hotelier.hotel.module.rh.dto.request.employe.UpdateEmployeRequest;
import projet_hotelier.hotel.module.rh.dto.response.employe.EmployeResponse;
import projet_hotelier.hotel.module.rh.model.personnel.EmployeModel;
import projet_hotelier.hotel.shared.dto.AuditDTO;
import projet_hotelier.hotel.shared.dto.TraceDTO;

import java.util.List;

@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        unmappedTargetPolicy = org.mapstruct.ReportingPolicy.ERROR,
        builder = @org.mapstruct.Builder(disableBuilder = true)
)
public interface EmployeMapper {

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "uuid", ignore = true)
    @Mapping(target = "dateCreation", ignore = true)
    @Mapping(target = "dateModification", ignore = true)
    @Mapping(target = "creePar", ignore = true)
    @Mapping(target = "modifiePar", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "actif", ignore = true)
    @Mapping(target = "supprime", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "organisationId", ignore = true)
    @Mapping(target = "hotelId", ignore = true)
    @Mapping(target = "metadataJson", ignore = true)
    @Mapping(target = "dateSortie", ignore = true)
    @Mapping(target = "motifSortie", ignore = true)
    @Mapping(target = "nomComplet", ignore = true)
    @Mapping(target = "nomUsuel", ignore = true)
    @Mapping(target = "lieuNaissance", ignore = true)
    @Mapping(target = "civilite", ignore = true)
    @Mapping(target = "etatCivil", ignore = true)
    @Mapping(target = "telephoneSecondaire", ignore = true)
    @Mapping(target = "whatsapp", ignore = true)
    @Mapping(target = "telegram", ignore = true)
    @Mapping(target = "linkedin", ignore = true)
    @Mapping(target = "ville", ignore = true)
    @Mapping(target = "codePostal", ignore = true)
    @Mapping(target = "region", ignore = true)
    @Mapping(target = "paysResidenceCode", ignore = true)
    @Mapping(target = "paysResidence", ignore = true)
    @Mapping(target = "paysNaissanceCode", ignore = true)
    @Mapping(target = "paysNaissance", ignore = true)
    @Mapping(target = "nationaliteCode", ignore = true)
    @Mapping(target = "fuseauHoraire", ignore = true)
    @Mapping(target = "posteAnglais", ignore = true)
    @Mapping(target = "service", ignore = true)
    @Mapping(target = "direction", ignore = true)
    @Mapping(target = "niveauHierarchique", ignore = true)
    @Mapping(target = "categorieProfessionnelle", ignore = true)
    @Mapping(target = "classification", ignore = true)
    @Mapping(target = "managerId", ignore = true)
    @Mapping(target = "managerNom", ignore = true)
    @Mapping(target = "responsableRhId", ignore = true)
    @Mapping(target = "responsableRhNom", ignore = true)
    @Mapping(target = "dateFinContrat", ignore = true)
    @Mapping(target = "regimeTravail", ignore = true)
    @Mapping(target = "tauxTravail", ignore = true)
    @Mapping(target = "typeEmploi", ignore = true)
    @Mapping(target = "teletravailAutorise", ignore = true)
    @Mapping(target = "pourcentageTeletravail", ignore = true)
    @Mapping(target = "deviseSalaire", ignore = true)
    @Mapping(target = "periodicitePaie", ignore = true)
    @Mapping(target = "salaireBrutAnnuel", ignore = true)
    @Mapping(target = "salaireNetMensuel", ignore = true)
    @Mapping(target = "salaireNetAnnuel", ignore = true)
    @Mapping(target = "tauxHoraire", ignore = true)
    @Mapping(target = "heuresHebdomadaires", ignore = true)
    @Mapping(target = "heuresMensuelles", ignore = true)
    @Mapping(target = "numeroPasseport", ignore = true)
    @Mapping(target = "numeroCarteIdentite", ignore = true)
    @Mapping(target = "numeroPermisConduire", ignore = true)
    @Mapping(target = "numeroCarteSejour", ignore = true)
    @Mapping(target = "numeroVisa", ignore = true)
    @Mapping(target = "numeroPermisTravail", ignore = true)
    @Mapping(target = "dateExpirationPermisTravail", ignore = true)
    @Mapping(target = "dateExpirationVisa", ignore = true)
    @Mapping(target = "dateExpirationCarteSejour", ignore = true)
    @Mapping(target = "iban", ignore = true)
    @Mapping(target = "bic", ignore = true)
    @Mapping(target = "banqueAdresse", ignore = true)
    @Mapping(target = "deviseCompte", ignore = true)
    @Mapping(target = "contactUrgenceLien", ignore = true)
    @Mapping(target = "contactUrgence2Nom", ignore = true)
    @Mapping(target = "contactUrgence2Telephone", ignore = true)
    @Mapping(target = "conjointNom", ignore = true)
    @Mapping(target = "conjointTelephone", ignore = true)
    @Mapping(target = "nombreEnfants", ignore = true)
    @Mapping(target = "enfantsDetails", ignore = true)
    @Mapping(target = "personneCharge", ignore = true)
    @Mapping(target = "niveauEtude", ignore = true)
    @Mapping(target = "dernierDiplome", ignore = true)
    @Mapping(target = "ecoleUniversite", ignore = true)
    @Mapping(target = "anneeDiplome", ignore = true)
    @Mapping(target = "specialite", ignore = true)
    @Mapping(target = "languesParlees", ignore = true)
    @Mapping(target = "competencesTechniques", ignore = true)
    @Mapping(target = "certifications", ignore = true)
    @Mapping(target = "scorePerformanceGlobal", ignore = true)
    @Mapping(target = "scorePerformanceAnnee", ignore = true)
    @Mapping(target = "dateDerniereEvaluation", ignore = true)
    @Mapping(target = "dateProchaineEvaluation", ignore = true)
    @Mapping(target = "statutEvaluation", ignore = true)
    @Mapping(target = "soldeCongesAcquis", ignore = true)
    @Mapping(target = "soldeCongesPris", ignore = true)
    @Mapping(target = "soldeCongesRestant", ignore = true)
    @Mapping(target = "soldeRtt", ignore = true)
    @Mapping(target = "nombreAbsencesNonJustifiees", ignore = true)
    @Mapping(target = "nombreRetards", ignore = true)
    @Mapping(target = "groupeSanguin", ignore = true)
    @Mapping(target = "allergies", ignore = true)
    @Mapping(target = "conditionsMedicales", ignore = true)
    @Mapping(target = "restrictionsTravail", ignore = true)
    @Mapping(target = "visiteMedicaleValide", ignore = true)
    @Mapping(target = "dateDerniereVisiteMedicale", ignore = true)
    @Mapping(target = "dateProchaineVisiteMedicale", ignore = true)
    @Mapping(target = "accidentsTravail", ignore = true)
    @Mapping(target = "niveauAcces", ignore = true)
    @Mapping(target = "permissions", ignore = true)
    @Mapping(target = "roles", ignore = true)
    @Mapping(target = "accesSystemeAutorise", ignore = true)
    @Mapping(target = "dateDebutAcces", ignore = true)
    @Mapping(target = "dateFinAcces", ignore = true)
    @Mapping(target = "badgesAcces", ignore = true)
    @Mapping(target = "consentementDonnees", ignore = true)
    @Mapping(target = "dateConsentement", ignore = true)
    @Mapping(target = "obligationsLegales", ignore = true)
    @Mapping(target = "conformitePays", ignore = true)
    @Mapping(target = "regimeFiscal", ignore = true)
    @Mapping(target = "paysFiscal", ignore = true)
    @Mapping(target = "tauxImposition", ignore = true)
    @Mapping(target = "cotisationsSociales", ignore = true)
    @Mapping(target = "historiqueAffectations", ignore = true)
    @Mapping(target = "mobiliteAutorisee", ignore = true)
    @Mapping(target = "preferencesMobilite", ignore = true)
    @Mapping(target = "statutOnboarding", ignore = true)
    @Mapping(target = "dateDebutOnboarding", ignore = true)
    @Mapping(target = "dateFinOnboarding", ignore = true)
    @Mapping(target = "checklistOnboarding", ignore = true)
    @Mapping(target = "statutOffboarding", ignore = true)
    @Mapping(target = "dateDebutOffboarding", ignore = true)
    @Mapping(target = "dateFinOffboarding", ignore = true)
    @Mapping(target = "checklistOffboarding", ignore = true)
    @Mapping(target = "detailsSortie", ignore = true)
    @Mapping(target = "typeSortie", ignore = true)
    @Mapping(target = "scoreEngagement", ignore = true)
    @Mapping(target = "scoreRisqueDepart", ignore = true)
    @Mapping(target = "predictionsIA", ignore = true)
    @Mapping(target = "recommandationsIA", ignore = true)
    @Mapping(target = "insightsAnalytics", ignore = true)
    @Mapping(target = "preferencesEmploye", ignore = true)
    @Mapping(target = "configurationPoste", ignore = true)
    @Mapping(target = "notesRh", ignore = true)
    @Mapping(target = "notesManager", ignore = true)
    EmployeModel toEntity(CreateEmployeRequest request);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "uuid", ignore = true)
    @Mapping(target = "matricule", ignore = true)
    @Mapping(target = "dateCreation", ignore = true)
    @Mapping(target = "dateModification", ignore = true)
    @Mapping(target = "creePar", ignore = true)
    @Mapping(target = "modifiePar", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "actif", ignore = true)
    @Mapping(target = "supprime", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "organisationId", ignore = true)
    @Mapping(target = "hotelId", ignore = true)
    @Mapping(target = "metadataJson", ignore = true)
    @Mapping(target = "nomComplet", ignore = true)
    @Mapping(target = "nomUsuel", ignore = true)
    @Mapping(target = "lieuNaissance", ignore = true)
    @Mapping(target = "civilite", ignore = true)
    @Mapping(target = "etatCivil", ignore = true)
    @Mapping(target = "telephoneSecondaire", ignore = true)
    @Mapping(target = "whatsapp", ignore = true)
    @Mapping(target = "telegram", ignore = true)
    @Mapping(target = "linkedin", ignore = true)
    @Mapping(target = "ville", ignore = true)
    @Mapping(target = "codePostal", ignore = true)
    @Mapping(target = "region", ignore = true)
    @Mapping(target = "paysResidenceCode", ignore = true)
    @Mapping(target = "paysResidence", ignore = true)
    @Mapping(target = "paysNaissanceCode", ignore = true)
    @Mapping(target = "paysNaissance", ignore = true)
    @Mapping(target = "nationaliteCode", ignore = true)
    @Mapping(target = "fuseauHoraire", ignore = true)
    @Mapping(target = "posteAnglais", ignore = true)
    @Mapping(target = "service", ignore = true)
    @Mapping(target = "direction", ignore = true)
    @Mapping(target = "niveauHierarchique", ignore = true)
    @Mapping(target = "categorieProfessionnelle", ignore = true)
    @Mapping(target = "classification", ignore = true)
    @Mapping(target = "managerId", ignore = true)
    @Mapping(target = "managerNom", ignore = true)
    @Mapping(target = "responsableRhId", ignore = true)
    @Mapping(target = "responsableRhNom", ignore = true)
    @Mapping(target = "dateFinContrat", ignore = true)
    @Mapping(target = "regimeTravail", ignore = true)
    @Mapping(target = "tauxTravail", ignore = true)
    @Mapping(target = "typeEmploi", ignore = true)
    @Mapping(target = "teletravailAutorise", ignore = true)
    @Mapping(target = "pourcentageTeletravail", ignore = true)
    @Mapping(target = "deviseSalaire", ignore = true)
    @Mapping(target = "periodicitePaie", ignore = true)
    @Mapping(target = "salaireBrutAnnuel", ignore = true)
    @Mapping(target = "salaireNetMensuel", ignore = true)
    @Mapping(target = "salaireNetAnnuel", ignore = true)
    @Mapping(target = "tauxHoraire", ignore = true)
    @Mapping(target = "heuresHebdomadaires", ignore = true)
    @Mapping(target = "heuresMensuelles", ignore = true)
    @Mapping(target = "numeroPasseport", ignore = true)
    @Mapping(target = "numeroCarteIdentite", ignore = true)
    @Mapping(target = "numeroPermisConduire", ignore = true)
    @Mapping(target = "numeroCarteSejour", ignore = true)
    @Mapping(target = "numeroVisa", ignore = true)
    @Mapping(target = "numeroPermisTravail", ignore = true)
    @Mapping(target = "dateExpirationPermisTravail", ignore = true)
    @Mapping(target = "dateExpirationVisa", ignore = true)
    @Mapping(target = "dateExpirationCarteSejour", ignore = true)
    @Mapping(target = "iban", ignore = true)
    @Mapping(target = "bic", ignore = true)
    @Mapping(target = "banqueAdresse", ignore = true)
    @Mapping(target = "deviseCompte", ignore = true)
    @Mapping(target = "contactUrgenceLien", ignore = true)
    @Mapping(target = "contactUrgence2Nom", ignore = true)
    @Mapping(target = "contactUrgence2Telephone", ignore = true)
    @Mapping(target = "conjointNom", ignore = true)
    @Mapping(target = "conjointTelephone", ignore = true)
    @Mapping(target = "nombreEnfants", ignore = true)
    @Mapping(target = "enfantsDetails", ignore = true)
    @Mapping(target = "personneCharge", ignore = true)
    @Mapping(target = "niveauEtude", ignore = true)
    @Mapping(target = "dernierDiplome", ignore = true)
    @Mapping(target = "ecoleUniversite", ignore = true)
    @Mapping(target = "anneeDiplome", ignore = true)
    @Mapping(target = "specialite", ignore = true)
    @Mapping(target = "languesParlees", ignore = true)
    @Mapping(target = "competencesTechniques", ignore = true)
    @Mapping(target = "certifications", ignore = true)
    @Mapping(target = "scorePerformanceGlobal", ignore = true)
    @Mapping(target = "scorePerformanceAnnee", ignore = true)
    @Mapping(target = "dateDerniereEvaluation", ignore = true)
    @Mapping(target = "dateProchaineEvaluation", ignore = true)
    @Mapping(target = "statutEvaluation", ignore = true)
    @Mapping(target = "soldeCongesAcquis", ignore = true)
    @Mapping(target = "soldeCongesPris", ignore = true)
    @Mapping(target = "soldeCongesRestant", ignore = true)
    @Mapping(target = "soldeRtt", ignore = true)
    @Mapping(target = "nombreAbsencesNonJustifiees", ignore = true)
    @Mapping(target = "nombreRetards", ignore = true)
    @Mapping(target = "groupeSanguin", ignore = true)
    @Mapping(target = "allergies", ignore = true)
    @Mapping(target = "conditionsMedicales", ignore = true)
    @Mapping(target = "restrictionsTravail", ignore = true)
    @Mapping(target = "visiteMedicaleValide", ignore = true)
    @Mapping(target = "dateDerniereVisiteMedicale", ignore = true)
    @Mapping(target = "dateProchaineVisiteMedicale", ignore = true)
    @Mapping(target = "accidentsTravail", ignore = true)
    @Mapping(target = "niveauAcces", ignore = true)
    @Mapping(target = "permissions", ignore = true)
    @Mapping(target = "roles", ignore = true)
    @Mapping(target = "accesSystemeAutorise", ignore = true)
    @Mapping(target = "dateDebutAcces", ignore = true)
    @Mapping(target = "dateFinAcces", ignore = true)
    @Mapping(target = "badgesAcces", ignore = true)
    @Mapping(target = "consentementDonnees", ignore = true)
    @Mapping(target = "dateConsentement", ignore = true)
    @Mapping(target = "obligationsLegales", ignore = true)
    @Mapping(target = "conformitePays", ignore = true)
    @Mapping(target = "regimeFiscal", ignore = true)
    @Mapping(target = "paysFiscal", ignore = true)
    @Mapping(target = "tauxImposition", ignore = true)
    @Mapping(target = "cotisationsSociales", ignore = true)
    @Mapping(target = "historiqueAffectations", ignore = true)
    @Mapping(target = "mobiliteAutorisee", ignore = true)
    @Mapping(target = "preferencesMobilite", ignore = true)
    @Mapping(target = "statutOnboarding", ignore = true)
    @Mapping(target = "dateDebutOnboarding", ignore = true)
    @Mapping(target = "dateFinOnboarding", ignore = true)
    @Mapping(target = "checklistOnboarding", ignore = true)
    @Mapping(target = "statutOffboarding", ignore = true)
    @Mapping(target = "dateDebutOffboarding", ignore = true)
    @Mapping(target = "dateFinOffboarding", ignore = true)
    @Mapping(target = "checklistOffboarding", ignore = true)
    @Mapping(target = "detailsSortie", ignore = true)
    @Mapping(target = "typeSortie", ignore = true)
    @Mapping(target = "scoreEngagement", ignore = true)
    @Mapping(target = "scoreRisqueDepart", ignore = true)
    @Mapping(target = "predictionsIA", ignore = true)
    @Mapping(target = "recommandationsIA", ignore = true)
    @Mapping(target = "insightsAnalytics", ignore = true)
    @Mapping(target = "preferencesEmploye", ignore = true)
    @Mapping(target = "configurationPoste", ignore = true)
    @Mapping(target = "notesRh", ignore = true)
    @Mapping(target = "notesManager", ignore = true)
    void updateEntity(@MappingTarget EmployeModel entity, UpdateEmployeRequest request);

    @Mapping(target = "audit", expression = "java(mapAudit(entity))")
    @Mapping(target = "trace", expression = "java(mapTrace(entity))")
    EmployeResponse toResponse(EmployeModel entity);

    List<EmployeResponse> toResponseList(List<EmployeModel> entities);

    default AuditDTO mapAudit(EmployeModel entity) {
        if (entity == null) return null;
        return AuditDTO.builder()
                .uuid(entity.getUuid())
                .dateCreation(entity.getDateCreation())
                .dateModification(entity.getDateModification())
                .creePar(entity.getCreePar())
                .modifiePar(entity.getModifiePar())
                .version(entity.getVersion())
                .actif(entity.getActif())
                .build();
    }

    default TraceDTO mapTrace(EmployeModel entity) {
        if (entity == null) return null;
        return TraceDTO.builder()
                .traceId(entity.getTraceId())
                .spanId(entity.getSpanId())
                .correlationId(entity.getCorrelationId())
                .requestId(entity.getRequestId())
                .operationId(entity.getOperationId())
                .idempotencyKey(entity.getIdempotencyKey())
                .sourceSystem(entity.getSourceSystem())
                .sourceIp(entity.getSourceIp())
                .userAgent(entity.getUserAgent())
                .build();
    }
}
