package projet_hotelier.hotel.module.rh.mapper.conge;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import projet_hotelier.hotel.module.rh.dto.request.conge.CreateCongeRequest;
import projet_hotelier.hotel.module.rh.dto.request.conge.UpdateCongeRequest;
import projet_hotelier.hotel.module.rh.dto.response.conge.CongeResponse;
import projet_hotelier.hotel.module.rh.model.conge.CongeModel;
import projet_hotelier.hotel.shared.dto.AuditDTO;
import projet_hotelier.hotel.shared.dto.TraceDTO;

import java.util.List;

@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        unmappedTargetPolicy = org.mapstruct.ReportingPolicy.ERROR,
        builder = @org.mapstruct.Builder(disableBuilder = true)
)
public interface CongeMapper {

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "uuid", ignore = true)
    @Mapping(target = "statutConge", constant = "EN_ATTENTE")
    @Mapping(target = "approuvePar", ignore = true)
    @Mapping(target = "dateApprobation", ignore = true)
    @Mapping(target = "dateCreation", ignore = true)
    @Mapping(target = "dateModification", ignore = true)
    @Mapping(target = "creePar", ignore = true)
    @Mapping(target = "modifiePar", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "actif", ignore = true)
    @Mapping(target = "supprime", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "organisationId", ignore = true)
    @Mapping(target = "hotelId", ignore = true)
    @Mapping(target = "metadataJson", ignore = true)
    @Mapping(target = "employeNom", ignore = true)
    @Mapping(target = "employeMatricule", ignore = true)
    @Mapping(target = "sousTypeConge", ignore = true)
    @Mapping(target = "natureConge", ignore = true)
    @Mapping(target = "heureDebut", ignore = true)
    @Mapping(target = "heureFin", ignore = true)
    @Mapping(target = "congéPartiel", ignore = true)
    @Mapping(target = "nombreJours", ignore = true)
    @Mapping(target = "nombreJoursOuvres", ignore = true)
    @Mapping(target = "nombreJoursCalendaires", ignore = true)
    @Mapping(target = "nombreHeures", ignore = true)
    @Mapping(target = "etapeWorkflow", ignore = true)
    @Mapping(target = "niveauValidation", ignore = true)
    @Mapping(target = "niveauValidationActuel", ignore = true)
    @Mapping(target = "justification", ignore = true)
    @Mapping(target = "commentairesEmploye", ignore = true)
    @Mapping(target = "commentairesValidateur", ignore = true)
    @Mapping(target = "soldeInitial", ignore = true)
    @Mapping(target = "soldeTotalPris", ignore = true)
    @Mapping(target = "soldeRestant", ignore = true)
    @Mapping(target = "approuveParNom", ignore = true)
    @Mapping(target = "dateHeureApprobation", ignore = true)
    @Mapping(target = "typeApprobation", ignore = true)
    @Mapping(target = "valideParManager", ignore = true)
    @Mapping(target = "valideParManagerNom", ignore = true)
    @Mapping(target = "dateValidationManager", ignore = true)
    @Mapping(target = "commentairesManager", ignore = true)
    @Mapping(target = "valideParRh", ignore = true)
    @Mapping(target = "valideParRhNom", ignore = true)
    @Mapping(target = "dateValidationRh", ignore = true)
    @Mapping(target = "commentairesRh", ignore = true)
    @Mapping(target = "valideParDirection", ignore = true)
    @Mapping(target = "valideParDirectionNom", ignore = true)
    @Mapping(target = "dateValidationDirection", ignore = true)
    @Mapping(target = "rejete", ignore = true)
    @Mapping(target = "rejetePar", ignore = true)
    @Mapping(target = "rejeteParNom", ignore = true)
    @Mapping(target = "dateRejet", ignore = true)
    @Mapping(target = "motifRejet", ignore = true)
    @Mapping(target = "annule", ignore = true)
    @Mapping(target = "annulePar", ignore = true)
    @Mapping(target = "dateAnnulation", ignore = true)
    @Mapping(target = "motifAnnulation", ignore = true)
    @Mapping(target = "impactService", ignore = true)
    @Mapping(target = "mesuresCompensation", ignore = true)
    @Mapping(target = "remplacementNecessaire", ignore = true)
    @Mapping(target = "remplacePar", ignore = true)
    @Mapping(target = "remplaceParNom", ignore = true)
    @Mapping(target = "paysCode", ignore = true)
    @Mapping(target = "reglementationApplicable", ignore = true)
    @Mapping(target = "conformeReglementation", ignore = true)
    @Mapping(target = "obligationsLegales", ignore = true)
    @Mapping(target = "recuperation", ignore = true)
    @Mapping(target = "dateRecuperation", ignore = true)
    @Mapping(target = "motifRecuperation", ignore = true)
    @Mapping(target = "reporte", ignore = true)
    @Mapping(target = "dateReportInitiale", ignore = true)
    @Mapping(target = "dateReportNouvelle", ignore = true)
    @Mapping(target = "motifReport", ignore = true)
    @Mapping(target = "niveauUrgence", ignore = true)
    @Mapping(target = "urgenceMedicale", ignore = true)
    @Mapping(target = "urgenceFamiliale", ignore = true)
    @Mapping(target = "notificationEnvoyee", ignore = true)
    @Mapping(target = "dateNotification", ignore = true)
    @Mapping(target = "rappelEnvoye", ignore = true)
    @Mapping(target = "dateRappel", ignore = true)
    @Mapping(target = "documentsJustificatifs", ignore = true)
    @Mapping(target = "certificatsMedicaux", ignore = true)
    @Mapping(target = "scoreConformite", ignore = true)
    @Mapping(target = "predictionsIA", ignore = true)
    @Mapping(target = "recommandationsIA", ignore = true)
    @Mapping(target = "metadataWorkflow", ignore = true)
    @Mapping(target = "notesInternes", ignore = true)
    @Mapping(target = "notesRh", ignore = true)
    CongeModel toEntity(CreateCongeRequest request);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "uuid", ignore = true)
    @Mapping(target = "employeId", ignore = true)
    @Mapping(target = "typeConge", ignore = true)
    @Mapping(target = "dateCreation", ignore = true)
    @Mapping(target = "dateModification", ignore = true)
    @Mapping(target = "creePar", ignore = true)
    @Mapping(target = "modifiePar", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "actif", ignore = true)
    @Mapping(target = "supprime", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "organisationId", ignore = true)
    @Mapping(target = "hotelId", ignore = true)
    @Mapping(target = "metadataJson", ignore = true)
    @Mapping(target = "employeNom", ignore = true)
    @Mapping(target = "employeMatricule", ignore = true)
    @Mapping(target = "sousTypeConge", ignore = true)
    @Mapping(target = "natureConge", ignore = true)
    @Mapping(target = "heureDebut", ignore = true)
    @Mapping(target = "heureFin", ignore = true)
    @Mapping(target = "congéPartiel", ignore = true)
    @Mapping(target = "nombreJours", ignore = true)
    @Mapping(target = "nombreJoursOuvres", ignore = true)
    @Mapping(target = "nombreJoursCalendaires", ignore = true)
    @Mapping(target = "nombreHeures", ignore = true)
    @Mapping(target = "etapeWorkflow", ignore = true)
    @Mapping(target = "niveauValidation", ignore = true)
    @Mapping(target = "niveauValidationActuel", ignore = true)
    @Mapping(target = "justification", ignore = true)
    @Mapping(target = "commentairesEmploye", ignore = true)
    @Mapping(target = "commentairesValidateur", ignore = true)
    @Mapping(target = "soldeInitial", ignore = true)
    @Mapping(target = "soldeTotalPris", ignore = true)
    @Mapping(target = "soldeRestant", ignore = true)
    @Mapping(target = "approuveParNom", ignore = true)
    @Mapping(target = "dateHeureApprobation", ignore = true)
    @Mapping(target = "typeApprobation", ignore = true)
    @Mapping(target = "valideParManager", ignore = true)
    @Mapping(target = "valideParManagerNom", ignore = true)
    @Mapping(target = "dateValidationManager", ignore = true)
    @Mapping(target = "commentairesManager", ignore = true)
    @Mapping(target = "valideParRh", ignore = true)
    @Mapping(target = "valideParRhNom", ignore = true)
    @Mapping(target = "dateValidationRh", ignore = true)
    @Mapping(target = "commentairesRh", ignore = true)
    @Mapping(target = "valideParDirection", ignore = true)
    @Mapping(target = "valideParDirectionNom", ignore = true)
    @Mapping(target = "dateValidationDirection", ignore = true)
    @Mapping(target = "rejete", ignore = true)
    @Mapping(target = "rejetePar", ignore = true)
    @Mapping(target = "rejeteParNom", ignore = true)
    @Mapping(target = "dateRejet", ignore = true)
    @Mapping(target = "motifRejet", ignore = true)
    @Mapping(target = "annule", ignore = true)
    @Mapping(target = "annulePar", ignore = true)
    @Mapping(target = "dateAnnulation", ignore = true)
    @Mapping(target = "motifAnnulation", ignore = true)
    @Mapping(target = "impactService", ignore = true)
    @Mapping(target = "mesuresCompensation", ignore = true)
    @Mapping(target = "remplacementNecessaire", ignore = true)
    @Mapping(target = "remplacePar", ignore = true)
    @Mapping(target = "remplaceParNom", ignore = true)
    @Mapping(target = "paysCode", ignore = true)
    @Mapping(target = "reglementationApplicable", ignore = true)
    @Mapping(target = "conformeReglementation", ignore = true)
    @Mapping(target = "obligationsLegales", ignore = true)
    @Mapping(target = "recuperation", ignore = true)
    @Mapping(target = "dateRecuperation", ignore = true)
    @Mapping(target = "motifRecuperation", ignore = true)
    @Mapping(target = "reporte", ignore = true)
    @Mapping(target = "dateReportInitiale", ignore = true)
    @Mapping(target = "dateReportNouvelle", ignore = true)
    @Mapping(target = "motifReport", ignore = true)
    @Mapping(target = "niveauUrgence", ignore = true)
    @Mapping(target = "urgenceMedicale", ignore = true)
    @Mapping(target = "urgenceFamiliale", ignore = true)
    @Mapping(target = "notificationEnvoyee", ignore = true)
    @Mapping(target = "dateNotification", ignore = true)
    @Mapping(target = "rappelEnvoye", ignore = true)
    @Mapping(target = "dateRappel", ignore = true)
    @Mapping(target = "documentsJustificatifs", ignore = true)
    @Mapping(target = "certificatsMedicaux", ignore = true)
    @Mapping(target = "scoreConformite", ignore = true)
    @Mapping(target = "predictionsIA", ignore = true)
    @Mapping(target = "recommandationsIA", ignore = true)
    @Mapping(target = "metadataWorkflow", ignore = true)
    @Mapping(target = "notesInternes", ignore = true)
    @Mapping(target = "notesRh", ignore = true)
    void updateEntity(@MappingTarget CongeModel entity, UpdateCongeRequest request);

    @Mapping(target = "audit", expression = "java(mapAudit(entity))")
    @Mapping(target = "trace", expression = "java(mapTrace(entity))")
    CongeResponse toResponse(CongeModel entity);

    List<CongeResponse> toResponseList(List<CongeModel> entities);

    default AuditDTO mapAudit(CongeModel entity) {
        if (entity == null) return null;
        return AuditDTO.builder()
                .uuid(entity.getUuid())
                .dateCreation(entity.getDateCreation())
                .dateModification(entity.getDateModification())
                .creePar(entity.getCreePar())
                .modifiePar(entity.getModifiePar())
                .version(entity.getVersion())
                .actif(entity.getActif())
                .build();
    }

    default TraceDTO mapTrace(CongeModel entity) {
        if (entity == null) return null;
        return TraceDTO.builder()
                .traceId(entity.getTraceId())
                .spanId(entity.getSpanId())
                .correlationId(entity.getCorrelationId())
                .requestId(entity.getRequestId())
                .operationId(entity.getOperationId())
                .idempotencyKey(entity.getIdempotencyKey())
                .sourceSystem(entity.getSourceSystem())
                .sourceIp(entity.getSourceIp())
                .userAgent(entity.getUserAgent())
                .build();
    }
}
